# Generated by Django 4.2.2 on 2023-06-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
